apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: iconrepo-backend-ingress
  namespace: default
spec:
  virtualhost:
    fqdn: api.iconrepo.local.com
  routes:
    - conditions:
      - prefix: /
      services:
        - name: iconrepo-backend
          port: 8080
