apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: content-delivery-ingress
  namespace: default
spec:
  virtualhost:
    fqdn: client.iconrepo.internal
  routes:
    - conditions:
      - prefix: /
      services:
        - name: iconrepo
          port: 8080
