structname: "{{.InterfaceName}}"
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  iconrepo/internal/app/services:
    config:
      dir: test/mocks
    interfaces:
      Repository: {}
