apiVersion: v1
kind: Service
metadata:
  name: iconrepo
  labels:
    app: iconrepo
spec:
  selector:
    app: iconrepo
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iconrepo
  name: iconrepo
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: iconrepo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: iconrepo
    spec:
      containers:
      - image: iconrepo:latest
        imagePullPolicy: Never
        name: iconrepo
        env:
        - name: ICON_REPO_CONFIG_FILE
          value: none
        - name: SERVER_HOSTNAME
          value: 0.0.0.0
        - name: SERVER_PORT
          value: "8080"
        - name: DB_HOST
          value: postgres
        - name: SESSION_DB_NAME
          value: session
        - name: AUTHENTICATION_TYPE
          value: oidc
        - name: OIDC_CLIENT_ID
          value: iconrepo
        - name: OIDC_CLIENT_SECRET
          value: 1jH1TlxHvnxpHYuj7rMy2floGMPqcPrj
        - name: OIDC_TOKEN_ISSUER
          value: http://keycloak:8080/realms/my-realm
        - name: OIDC_CLIENT_REDIRECT_BACK_URL
          value: http://iconrepo:8080/openid-callback
        - name: GITLAB_NAMESPACE_PATH
          value: ''
        - name: LOG_LEVEL
          value: debug
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /app-info
            port: 8080
        resources:
          requests:
            memory: "1024Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "500m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
