apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: content-delivery-ingress
  namespace: default
spec:
  virtualhost:
    fqdn: iconrepo.local.com
  routes:
    - conditions:
      - prefix: /api
      services:
        - name: iconrepo-backend
          port: 8080
    - conditions:
      - prefix: /openid-callback
      services:
        - name: iconrepo-backend
          port: 8080
    - conditions:
      - prefix: /
      services:
        - name: iconrepo
          port: 8080
