apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: content-delivery-ingress
  namespace: default
spec:
  virtualhost:
    fqdn: iconrepo.local.com
  routes:
    - conditions:
      - prefix: /api
      services:
        - name: iconrepo-backend
          port: 8080
      pathRewritePolicy:
        replacePrefix:
        - prefix: /api
          replacement: /
      cookieRewritePolicies: # We're not directing to REWRITE here actually, we're directing NOT to REWRITE
      - name: mysession
        pathRewrite:
          value: /
    - conditions:
      - prefix: /openid-callback
      services:
        - name: iconrepo-backend
          port: 8080
    - conditions:
      - prefix: /
      services:
        - name: iconrepo
          port: 8080
