apiVersion: v1
kind: Service
metadata:
  name: iconrepo
  labels:
    app: iconrepo
spec:
  selector:
    app: iconrepo
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iconrepo
  name: iconrepo
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: iconrepo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: iconrepo
    spec:
      containers:
      - image: iconrepo:latest
        imagePullPolicy: Never
        name: iconrepo
        env:
        - name: ICONREPO_CONFIG_FILE
          value: /etc/config/config.json
        - name: OIDC_CLIENT_SECRET
          valueFrom:
           secretKeyRef:
             name: iconrepo
             key: oidc-client-secret
        - name: GITLAB_ACCESS_TOKEN
          valueFrom:
           secretKeyRef:
             name: iconrepo
             key: gitlab-access-token
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /app-info
            port: 8080
        resources:
          requests:
            memory: "1024Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "500m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config-volume
          configMap:
            name: iconrepo
        - name: secrets-volume
          

