# https://github.com/mrparkers/terraform-provider-keycloak/blob/master/docker-compose.yml
version: "3"
volumes:
  postgres:
services:
  redis-server:
    image: redis
    command: --loglevel debug
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy
    command:
      - --http-address=0.0.0.0:4180
      - --provider=keycloak-oidc
      - --client-id=iconrepo
      - --client-secret=Xb5BtE9RvMWCjJGfeMJDYOWIZGKSMm3z
      - --redirect-url=http://$MY_IP:4180/oauth2/callback
      - --oidc-issuer-url=http://$MY_IP:8080/auth/realms/my-realm
      - --oidc-extra-audience=account
      # - --allowed-role=<realm role name> // Optional, required realm role
      # - --allowed-role=<client id>:<client role name> // Optional, required client role
      - --reverse-proxy=true
      - --cookie-httponly=true
      - --cookie-secure=false
      - --cookie-secret=Au4Zozt44vz67jY2Fwm7TBeCarz6uL1g964YiFowTBk=
      - --email-domain=*
      - --insecure-oidc-allow-unverified-email=true
      # - --cookie-domain=.whatevermydomainishere.com
      # - --whitelist-domain=[.whatevermydomainishere.com,.otherdomain.com,.foobardomain.io]]
      - --request-logging=false
      - --auth-logging=false
      - --standard-logging=true
      - --session-store-type=redis
      - --redis-connection-url=redis://redis-server/2
      - --upstream=http://$MY_IP:8091/
      - --pass-authorization-header=true
    entrypoint:
      - oauth2-proxy
    ports:
      - 4180:4180
