apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: kube-system  # <-- you can place it somewhere else
  labels:
    app: postgres
spec:
 ports:
 - protocol: TCP
   port: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres
subsets: 
- addresses:
  - ip: 192.168.1.189
  ports:
  - port: 5432
